= Техническое задание
Алена О <alignova@gmail.com> 2021-04-12
:appversion: 1.0.0
:hardbreaks:

== Введение
=== Сокращения
Бот - разрабатываемый продукт
Чат - чат мессенджера Telegram

=== Описание продукта
Бот представляет собой Telegram бота для отслеживания сообщений участников в чатах.

=== Назначение
Бот предназначен для модерирования сообщений в чатах типа "Барахолка".

=== Область действия
Бот добавляется в общественные чаты.

=== Ссылки
Мессенджер Telegram - https://telegram.org/

== Общее описание
=== Функции продукта


== Детальные требования
=== Функциональные требования
Бот производит следующие действия в чате:

- Удаляет сообщения о входе пользователей:
User _joined the group_
User1 _invited_ User2
- Удаляет видео файлы с сообщениями, отправленными вместе с видео
- Удаляет сообщения со ссылками на сайты avito.ru, youla.ru
- Удаляет gif файлы
- Проверяет существования дуликата фотографии в текущем чате и действует по следующему сценарию:
* если фотография отправлена впервые, то не происходит никаких действий
* если в чате находится дубликат фотографии и она отправлена менее месяца назад, то удаляется новая фотография
* если дубликат фотографии отправлен более месяца назад, то удаляется дубликат